import { useApiQuery, useApiMutation, useApiMutationById, useApiDelete } from './useQueries';

export const useProducts = (params) => useApiQuery({ endpoint: '/products', params, key: 'products' });
export const useProduct = (id) => useApiQueryById({ endpoint: '/products', id, key: 'product' });
export const useCreateProduct = () => useApiMutation({ endpoint: '/products', invalidate: ['products'] });
export const useUpdateProduct = () => useApiMutationById({ endpoint: '/products', invalidate: ['products'] });
export const useDeleteProduct = () => useApiDelete({ endpoint: '/products', invalidate: ['products'] });
export const useProductStats = () => useApiQuery({ endpoint: '/products/stats', key: 'productStats' });
export const useLowStockProducts = () => useApiQuery({ endpoint: '/products/low-stock', key: 'lowStock' });
export const useCategories = () => useApiQuery({ endpoint: '/categories', key: 'categories' });
export const useCategoryTree = () => useApiQuery({ endpoint: '/categories/tree', key: 'categoryTree' });
export const useCreateCategory = () => useApiMutation({ endpoint: '/categories', invalidate: ['categories', 'categoryTree'] });
export const useUpdateCategory = () => useApiMutationById({ endpoint: '/categories', invalidate: ['categories', 'categoryTree'] });
export const useDeleteCategory = () => useApiDelete({ endpoint: '/categories', invalidate: ['categories', 'categoryTree'] });
export const useCoupons = () => useApiQuery({ endpoint: '/coupons', key: 'coupons' });
export const useCreateCoupon = () => useApiMutation({ endpoint: '/coupons', invalidate: ['coupons'] });
export const useUpdateCoupon = () => useApiMutationById({ endpoint: '/coupons', invalidate: ['coupons'] });
export const useDeleteCoupon = () => useApiDelete({ endpoint: '/coupons', invalidate: ['coupons'] });
export const useValidateCoupon = () => useApiMutation({ endpoint: '/coupons/validate', method: 'POST' });
export const useReviews = (params) => useApiQuery({ endpoint: '/reviews', params, key: 'reviews' });
export const useProductReviews = (productId, params) => useApiQuery({ endpoint: `/reviews/product/${productId}`, params, key: ['reviews', productId] });
export const useDeleteReview = () => useApiDelete({ endpoint: '/reviews', invalidate: ['reviews'] });
export const useOrders = (params) => useApiQuery({ endpoint: '/orders', params, key: 'orders' });
export const useMyOrders = (params) => useApiQuery({ endpoint: '/orders/my-orders', params, key: 'myOrders' });
export const useOrder = (id) => useApiQueryById({ endpoint: '/orders', id, key: 'order' });
export const useCreateOrder = () => useApiMutation({ endpoint: '/orders', invalidate: ['orders', 'myOrders'] });
export const useUpdateOrderStatus = () => useApiMutationById({ endpoint: '/orders/status', invalidate: ['orders'] });
export const useOrderStats = () => useApiQuery({ endpoint: '/orders/stats', key: 'orderStats' });
export const useUsers = (params) => useApiQuery({ endpoint: '/users', params, key: 'users' });
export const useUserStats = () => useApiQuery({ endpoint: '/users/stats', key: 'userStats' });
export const useSettings = () => useApiQuery({ endpoint: '/settings', key: 'settings' });
export const useUpdateSettings = () => useApiMutation({ endpoint: '/settings', method: 'PUT', invalidate: ['settings'] });
